name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DIFY_WEB_IMAGE_NAME: ${{ vars.DIFY_WEB_IMAGE_NAME || 'langgenius/dify-web' }}
  DIFY_API_IMAGE_NAME: ${{ vars.DIFY_API_IMAGE_NAME || 'langgenius/dify-api' }}
  ALIYUN_REGISTRY_URL: 'crpi-qha9zod7jj1h7qwo.cn-beijing.personal.cr.aliyuncs.com'  # 阿里云镜像仓库地址

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Alibaba Cloud Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ALIYUN_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: checkout repo
        uses: actions/checkout@v2

      - name: Set up Make
        run: sudo apt-get install -y make

      - name: Run Makefile
        run: make build-push-all